# Generated by Django 3.2.9 on 2023-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_additional_information_image_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner')),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('link', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Banner_area',
                'verbose_name_plural': 'first banner area',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(choices=[('ГОРЯЧИЕ ПРЕДЛОЖЕНИЯ', 'ГОРЯЧИЕ ПРЕДЛОЖЕНИЯ'), ('НОВЫЕ ПОСТУПЛЕНИЯ', 'НОВЫЕ ПОСТУПЛЕНИЯ'), ('НОВЫЕ ПРЕДЛОЖЕНИЯ', 'НОВЫЕ ПРЕДЛОЖЕНИЯ')], default='ГОРЯЧИЕ ПРЕДЛОЖЕНИЯ', max_length=100)),
                ('image', models.ImageField(upload_to='media/slider')),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('link', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'sliders',
            },
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'sections'},
        ),
    ]
