# Generated by Django 3.2.9 on 2023-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20230407_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_area',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
