# Generated by Django 3.2.9 on 2023-05-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20230519_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_information',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
