# Generated by Django 3.2.9 on 2023-05-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_auto_20230521_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='marketplace.product'),
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='specification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product'),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product'),
        ),
    ]
