# Generated by Django 3.2.9 on 2023-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20230521_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/product'),
        ),
    ]
