# Generated by Django 3.2.9 on 2023-05-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_image_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_product',
            name='thumbnail',
        ),
    ]
