# Generated by Django 3.2.9 on 2023-05-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_remove_image_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_information',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
        migrations.AlterField(
            model_name='image_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
    ]
