# Generated by Django 3.2.9 on 2023-05-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_alter_product_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ManyToManyField(blank=True, to='marketplace.Section'),
        ),
    ]
