# Generated by Django 3.2.9 on 2023-05-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_auto_20230522_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
