# Generated by Django 3.2.9 on 2023-06-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='Reciepient',
            new_name='reciepient',
        ),
    ]
