# Generated by Django 3.2.9 on 2023-06-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230530_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
