# Generated by Django 3.2.9 on 2023-04-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
